### PR TITLE
add patches from laser_scan_mather and fixed some of CMakeLists.txt

### PR DESCRIPTION
**Pull request by k-okada**
-  add cm_icp_xy from  https://github.com/ccny-ros-pkg/scan_tools/tree/indigo/laser_scan_matcher/csm/patches
-  sm/CMakeLists.txt add -fPIC (relocation R_X86_64_32 against '.rodata' can  not be used when making a shared object; recompile with -fPIC)
- sm/CMakeLists.txt use TARGETS instaed of PROGRAMS, this fails if you compile on different directory 
- package.xml : add libgsl to run_depend see https://github.com/AndreaCensi/csm/blob/master/sm/pkg-config/csm.pc.in#L7

### CODE REVIEW

**Comment by 130s** [comment]
Thank you @k-okada 
I believe this PR is intended for ROS' package [laser_scan_matcher](http://wiki.ros.org/laser_scan_matcher). If so, I tried to use `csm_eigen` branch instead of master (for my decision, please see https://github.com/AndreaCensi/csm/pull/11#issue-112236566). If that makes sense, I'll cherry-pick your changes into csm_eigen branch.

**Comment by k-okada** [comment]
ok, if master is developed branch and csm_eigen is the freezes version as of 2013 with package.xml, I should  add this to csm_eigen, but if so why you added package.xml to master branch?

**Comment by k-okada** [comment]
diff between master and csm_eigen https://github.com/AndreaCensi/csm/compare/master...csm_eigen

did we use csm_eigen branch for current ros dep files, which is installed within laser_scan_mathcer ?
they uses
https://github.com/ccny-ros-pkg/scan_tools/blob/indigo/laser_scan_matcher/csm/GetCSM.cmake
and seems to using
https://github.com/AndreaCensi/csm/commit/56919d39f69d1d91c4a909750ff8516c42b3f0e9
commit. it seems within master branch

If we use eigen version, we may have to add eigen to package.xml, and adding gsl in my commit was wrong

**Comment by k-okada** [comment]
sorry https://github.com/AndreaCensi/csm/compare/master...56919d39f69d1d91c4a909750ff8516c42b3f0e9 https://github.com/AndreaCensi/csm/commit/56919d39f69d1d91c4a909750ff8516c42b3f0e9 is not within master buranch, but is is totally different from HEAD of csm_eigen branch, now sure what's happend

https://github.com/AndreaCensi/csm/tree/56919d39f69d1d91c4a909750ff8516c42b3f0e9
https://github.com/AndreaCensi/csm/tree/csm_eigen

**Comment by k-okada** [comment]
I may overlooked something so do not confident on this, but my conclusion at this moment is;

- current ros package uses 56919d39f69d1d91c4a909750ff8516c42b3f0e9
- that is in master branch, one commit before https://github.com/AndreaCensi/csm/commit/7659c7e742073067ed3c6eabe411d976be121df0
- so using csm_eigen is not correct, use master instead


screenshot from 2015-11-03 19 56 25
screenshot from 2015-11-03 19 56 29
screenshot from 2015-11-03 19 56 31

**Comment by AndreaCensi** [comment]
Just to clarify: essentially the master branch and the eigen branch have diverged. The eigen branch was developed by Kuka and was never meant to be merged back into master.

**Comment by k-okada** [comment]
are you ok with
https://github.com/k-okada/csm/commit/17768c9f2c7b039832eb71c6d3d1796b3bbc7e4e,
which is originally at
https://github.com/ccny-ros-pkg/scan_tools/tree/indigo/laser_scan_matcher/csm/patches

--
◉ Kei Okada

**Comment by 130s** [comment]
Sorry for the confusion.
I think we can use `master` branch instead of `csm_eigen`; as I mentioned in https://github.com/AndreaCensi/csm/pull/11#issue-112236566, only reason I used csm_eigen was because I assumed eigen would work better in ROS, but staying along with `master` sounds the right way to go. So +1 for this PR.

**Comment by k-okada** [comment]
On Wed, Nov 4, 2015 at 9:51 AM, Andrea Censi <notifications@github.com> 
wrote:

> The eigen branch was developed by Kuka and was never meant to be merged 
> back into master.


so kuka did not like gsl license, am I correct?

--
◉ Kei Okada

**Comment by AndreaCensi** [comment]
Yes, that was one of the issues.

**Pull request merged**
